apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: jaysney/techtrends:latest
          ports:
            - containerPort: 3111
          resources: {{ .Values.resources }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
