apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: techtrends
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3111
  type: ClusterIP
