apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
#  destination:
#    namespace: sandbox
#    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
      chart: techtrends-chart
    repoURL: https://github.com/JakeBx/nd064_course_1.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
